---
- name: check for the access
  when: action == "grant"
- name: Add a new developer
  user:
    name: developer
    comment: "Developing team user"
    shell: /bin/bash
  tags:
    - add

- name: Give SSH access
  authorized_key:
    user: developer
    state: present
    key: "{{ lookup('file', '../../../sshkeys/developer/id_rsa.pub') }}"
  tags:
    - grant

- name: check for the access
  when: action == "revoke"
- name: Revoke SSH access
  authorized_key:
    user: developer
    state: absent
    key: "{{ lookup('file', '../../../sshkeys/developer/id_rsa.pub') }}"
  tags:
    - revoke

- name: Remove user
  user:
    name: developer
    state: absent
    remove: yes
  tags:
    - remove
